# -*- coding: utf-8 -*-
"""TOPSIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ma7pVwPHsyT0Fnz6lRm_aEBCHtdsWquo
"""

!pip install pandas numpy

from google.colab import files
uploaded = files.upload()

import os
os.listdir()

import pandas as pd
import numpy as np
def basic_topsis(input_file, weights, impacts):

    data = pd.read_csv(input_file)

    decision_matrix = data.iloc[:, 1:]

    # Normalize
    norm = decision_matrix / np.sqrt((decision_matrix**2).sum())

    # Convert weights
    weights = np.array(weights)

    weighted_matrix = norm * weights

    ideal_best = []
    ideal_worst = []

    for i in range(len(impacts)):
        if impacts[i] == '+':
            ideal_best.append(weighted_matrix.iloc[:, i].max())
            ideal_worst.append(weighted_matrix.iloc[:, i].min())
        else:
            ideal_best.append(weighted_matrix.iloc[:, i].min())
            ideal_worst.append(weighted_matrix.iloc[:, i].max())

    ideal_best = np.array(ideal_best)
    ideal_worst = np.array(ideal_worst)

    dist_best = np.sqrt(((weighted_matrix - ideal_best)**2).sum(axis=1))
    dist_worst = np.sqrt(((weighted_matrix - ideal_worst)**2).sum(axis=1))

    score = dist_worst / (dist_best + dist_worst)

    data['Topsis Score'] = score
    data['Rank'] = score.rank(ascending=False)

    return data

!python topsis.py data.csv "1,1,1,2,1" "+,+,-,+,+" output.csv

# Commented out IPython magic to ensure Python compatibility.
# %%writefile topsis.py
# import sys
# import pandas as pd
# import numpy as np
# 
# def topsis(input_file, weights, impacts, output_file):
# 
#     # 1. File Handling
#     try:
#         data = pd.read_csv(input_file)
#     except FileNotFoundError:
#         print("Error: File not found.")
#         sys.exit(1)
# 
#     # 2. Check minimum columns
#     if data.shape[1] < 3:
#         print("Error: Input file must contain at least three columns.")
#         sys.exit(1)
# 
#     decision_matrix = data.iloc[:, 1:]
# 
#     # 3. Check numeric values
#     if not np.issubdtype(decision_matrix.values.dtype, np.number):
#         print("Error: From second column onwards, all values must be numeric.")
#         sys.exit(1)
# 
#     # 4. Split weights and impacts
#     weights = weights.split(',')
#     impacts = impacts.split(',')
# 
#     # 5. Length validation
#     if len(weights) != decision_matrix.shape[1] or len(impacts) != decision_matrix.shape[1]:
#         print("Error: Number of weights, impacts and columns must be same.")
#         sys.exit(1)
# 
#     # 6. Convert weights
#     try:
#         weights = np.array([float(w) for w in weights])
#     except:
#         print("Error: Weights must be numeric.")
#         sys.exit(1)
# 
#     # 7. Check impacts
#     for impact in impacts:
#         if impact not in ['+', '-']:
#             print("Error: Impacts must be '+' or '-'.")
#             sys.exit(1)
# 
#     # 8. Normalize
#     norm = decision_matrix / np.sqrt((decision_matrix ** 2).sum())
# 
#     # 9. Weighted matrix
#     weighted_matrix = norm * weights
# 
#     # 10. Ideal best and worst
#     ideal_best = []
#     ideal_worst = []
# 
#     for i in range(len(impacts)):
#         if impacts[i] == '+':
#             ideal_best.append(weighted_matrix.iloc[:, i].max())
#             ideal_worst.append(weighted_matrix.iloc[:, i].min())
#         else:
#             ideal_best.append(weighted_matrix.iloc[:, i].min())
#             ideal_worst.append(weighted_matrix.iloc[:, i].max())
# 
#     ideal_best = np.array(ideal_best)
#     ideal_worst = np.array(ideal_worst)
# 
#     # 11. Distance calculation
#     distance_best = np.sqrt(((weighted_matrix - ideal_best) ** 2).sum(axis=1))
#     distance_worst = np.sqrt(((weighted_matrix - ideal_worst) ** 2).sum(axis=1))
# 
#     # 12. Topsis score
#     score = distance_worst / (distance_best + distance_worst)
# 
#     # 13. Ranking
#     data['Topsis Score'] = score
#     data['Rank'] = score.rank(method='max', ascending=False).astype(int)
# 
#     # 14. Save output
#     data.to_csv(output_file, index=False)
# 
# 
# if __name__ == "__main__":
# 
#     # Check correct number of parameters
#     if len(sys.argv) != 5:
#         print("Usage: python topsis.py <InputDataFile> <Weights> <Impacts> <OutputFileName>")
#         sys.exit(1)
# 
#     input_file = sys.argv[1]
#     weights = sys.argv[2]
#     impacts = sys.argv[3]
#     output_file = sys.argv[4]
# 
#     topsis(input_file, weights, impacts, output_file)

"""Now that `topsis.py` has been created, you can run the cell `wYXhd4GM6c60` again, and it should execute successfully."""

df_excel = pd.read_excel('data.xlsx')
df_excel.to_csv('data.csv', index=False)
print('Converted data.xlsx to data.csv')

topsis(
    "data.csv",
    "1,1,1,2,1",
    "+,+,-,+,+",
    "output.csv"
)

!python topsis.py /content/data.csv "1,1,1,2" "+,+,-,+" /content/output.csv

import pandas as pd
pd.read_csv("output.csv")

from google.colab import files
files.download("output.csv")

!python topsis.py data.csv "1,1,1,2,1" "+,+,-,+,+" output.csv